### ISSUE TITLE
Question on the resources.tar.xz

### ISSUE THREAD

**Issue by wgmao** [jzhoulab/puffin_manuscript#2]
Thank you for keeping things organized! I was able to download the resource files following the instructions. After browsing the files included, I have a couple of questions regarding the following files: `agg.minus.bw.bedgraph.bw` and `agg.plus.bw.bedgraph.bw`.

1. My understanding is that these two files are strand-specific CAGE profiles after aggregation. If so, are they based on the CAGE profiles from FANTOM, ENCODE or both cohorts? Additionally, what raw profiles were included to generate these two tracks?
2. Do these profiles correspond to the experimental track on the web portal at https://puffin.zhoulab.io/?

Thanks!

**Comment by jzthree** [comment]
1. These are the aggregated strand-specific FANTOM CAGE files. Essentially all human CAGE files from `https://fantom.gsc.riken.jp/5/datafiles/latest/basic/` but not including LQhCAGE. We have separate bw files for ENCODE CAGE and other techniques.
2. Yes

**Comment by wgmao** [comment]
Thank you!
